name: 'send notice'
description: 'https://developer.work.weixin.qq.com/document/path/90253'

inputs:
    key:
        description: 'Webhook Key'
        required: false
        default: ''

    source:
        description: |
            Where the notice comes from: JSON format required
            Example: '{ "name": "You APP Name", "icon": "icon_url", "color": "RED" }'
        required: false
        default: 'null'

    main:
        description: |
            Main content of the notice: JSON format required
            Example: '{ "title": "Main Title", "content": "Main content of the notice" }'
        required: true

    emphasis:
        description: |
            Emphasis of the notice: JSON format required
            Example: '{ "title": "Emphasis Title", "content": "Emphasis content" }'
        required: false
        default: 'null'

    files:
        description: |
            Newline-delimited list of path globs for asset files to upload
            FILENAME_1,MEDIA_ID_1\nFILENAME_2,MEDIA_ID_2\nFILENAME_N,MEDIA_ID_N\n...
        required: false
        default: ''

    action:
        description: 'Click notice to jump to the specified URL.'
        required: false
        default: ''

runs:
    using: 'node20'
    main: '../../dist/send/notice/index.js'