on:
    workflow_dispatch:
        inputs:
            version:
                description: 'The version number for the release'
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Create new release branch
                run: |
                    NEW_BRANCH="release-v${{ github.event.inputs.version }}"
                    git checkout -b $NEW_BRANCH
                    echo "branch=$NEW_BRANCH" >> $GITHUB_ENV

            -   name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: '20'

            -   name: Install dependencies
                run: npm install

            -   name: Build
                run: npm run build

            -   name: Commit changes
                run: |
                    git config user.name "github-actions[bot]"
                    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                    git add -f dist
                    git commit -m "chore: update generated files [skip ci]" || echo "No changes to commit"
                    git push origin ${{ env.branch }}

            -   name: Create GitHub Release
                uses: softprops/action-gh-release@v2
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: v${{ github.event.inputs.version }}
                    draft: false
                    prerelease: false
                    target_commitish: ${{ env.branch }}
